import sys
sys.path.append('C:/Dev/Autofire')

# Force AutoFire to create output
from cad_core.intelligence.pdf_analyzer import PDFConstructionAnalyzer

analyzer = PDFConstructionAnalyzer()
result = analyzer.analyze_construction_set('C:/Dev/Autofire/Projects/floorplan-sample.pdf')

# Force write to file
f = open('autofire_forced_output.txt', 'w')
f.write('AUTOFIRE AI FORCED OUTPUT\n')
f.write('Project: ' + str(result.project_name) + '\n')
f.write('Pages: ' + str(result.total_pages) + '\n')
f.write('Floor Plans: ' + str(len(result.floor_plans)) + '\n')
f.write('Analysis Type: ' + str(type(result)) + '\n')
f.write('Generated by: ' + str(type(analyzer)) + '\n')
f.close()

print('Forced output written to autofire_forced_output.txt')