"""Title block exporter: generate print-friendly SVG and optional PNG/PDF.

Behavior:
- Always writes a vector `title_block.svg` with clear title block fields.
- If cairosvg is available, uses it to render PNG and/or PDF at high fidelity.
- If cairosvg isn't installed:
    - For PNG: falls back to Pillow to create a placeholder PNG noting the SVG.
    - For PDF: falls back to reportlab to place basic text outlines.

This design keeps CI/dev robust without hard optional deps, while producing the
best available outputs when libraries are present.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any  # noqa: F401  (for future expansion if needed)

try:
    # Optional imports; used opportunistically
    import cairosvg  # type: ignore
except Exception:  # pragma: no cover - handled at runtime
    cairosvg = None  # type: ignore

try:
    from PIL import Image  # type: ignore
    from PIL import ImageDraw, ImageFont  # type: ignore
except Exception:  # pragma: no cover - handled at runtime
    Image = None  # type: ignore
    ImageDraw = None  # type: ignore
    ImageFont = None  # type: ignore

try:
    from reportlab.lib.pagesizes import letter  # type: ignore
    from reportlab.pdfgen import canvas  # type: ignore
except Exception:  # pragma: no cover - handled at runtime
    letter = None  # type: ignore
    canvas = None  # type: ignore

SVG_TEMPLATE = """<?xml version='1.0' encoding='utf-8'?>
<svg xmlns='http://www.w3.org/2000/svg' width='1654' height='1275' viewBox='0 0 1654 1275'>
  <rect width='100%' height='100%' fill='#ffffff' />
  <rect x='24' y='24' width='1606' height='1227' fill='none' stroke='#222' stroke-width='2' />

  <!-- Title block area -->
  <rect x='24' y='1024' width='1606' height='227' fill='#f7f7f7' stroke='#ccc' stroke-width='1'/>
  <!-- Company/Logo box -->
  <rect x='1420' y='1040' width='190' height='90' fill='none' stroke='#bbb' stroke-width='1'/>
  <text x='1432' y='1095' font-family='Segoe UI, Arial, sans-serif' font-size='18' fill='#333'>{company}</text>

  <text x='48' y='1064' font-family='Segoe UI, Arial, sans-serif' font-size='28' fill='#111'>Project:</text>
  <text x='180' y='1064' font-family='Segoe UI, Arial, sans-serif' font-size='28' fill='#111'>{project_name}</text>

  <text x='48' y='1104' font-family='Segoe UI, Arial, sans-serif' font-size='20' fill='#333'>Client:</text>
  <text x='180' y='1104' font-family='Segoe UI, Arial, sans-serif' font-size='20' fill='#333'>{client}</text>

  <text x='48' y='1144' font-family='Segoe UI, Arial, sans-serif' font-size='20' fill='#333'>Sheet:</text>
  <text x='180' y='1144' font-family='Segoe UI, Arial, sans-serif' font-size='20' fill='#333'>{sheet_name}</text>

  <text x='1020' y='1064' font-family='Segoe UI, Arial, sans-serif' font-size='18' fill='#333'>Generated by {product}</text>
  <text x='1020' y='1100' font-family='Segoe UI, Arial, sans-serif' font-size='16' fill='#666'>Version {version}</text>
  <text x='1020' y='1132' font-family='Segoe UI, Arial, sans-serif' font-size='16' fill='#666'>Prepared by {author}</text>
  <text x='1020' y='1164' font-family='Segoe UI, Arial, sans-serif' font-size='16' fill='#666'>Date {date}</text>

  <!-- small metadata table -->
  <rect x='48' y='1176' width='1400' height='56' fill='none' stroke='#ddd' stroke-width='1'/>
  <text x='60' y='1208' font-family='Segoe UI, Arial, sans-serif' font-size='14' fill='#444'>Job #: {job_number}</text>
  <text x='300' y='1208' font-family='Segoe UI, Arial, sans-serif' font-size='14' fill='#444'>Rev: {revision}</text>

</svg>
"""


def _build_svg(meta: dict[str, str]) -> str:
    """Fill the SVG template with metadata and return text."""
    defaults = {
        "project_name": meta.get("project_name", "Untitled Project"),
        "client": meta.get("client", ""),
        "sheet_name": meta.get("sheet_name", "Sheet 1"),
        "author": meta.get("author", ""),
        "date": meta.get("date", ""),
        "product": meta.get("product", "AlarmForge"),
        "version": meta.get("version", "0.0.0"),
        "job_number": meta.get("job_number", ""),
        "revision": meta.get("revision", ""),
        "company": meta.get("company", meta.get("product", "AlarmForge")),
    }
    return SVG_TEMPLATE.format(**defaults)


def _try_write_png(svg_text: str, out_path: Path) -> bool:
    """Attempt to write PNG from SVG. Return True on success."""
    # Preferred: cairosvg
    if cairosvg is not None:
        try:
            png_bytes = cairosvg.svg2png(bytestring=svg_text.encode("utf-8"), output_width=1654, output_height=1275)
            out_path.write_bytes(png_bytes)
            return True
        except Exception:
            pass
    # Fallback: placeholder via Pillow
    if Image is not None:
        try:
            img = Image.new("RGB", (1654, 1275), color=(255, 255, 255))
            if ImageDraw is not None and ImageFont is not None:
                draw = ImageDraw.Draw(img)
                f = ImageFont.load_default()
                draw.text((20, 20), "See title_block.svg for full vector title block.", fill=(0, 0, 0), font=f)
            img.save(out_path)
            return True
        except Exception:
            pass
    return False


def _try_write_pdf(svg_text: str, out_path: Path, meta: dict[str, str]) -> bool:
    """Attempt to write PDF from SVG/meta. Return True on success."""
    # Preferred: cairosvg direct conversion
    if cairosvg is not None:
        try:
            pdf_bytes = cairosvg.svg2pdf(bytestring=svg_text.encode("utf-8"))
            out_path.write_bytes(pdf_bytes)
            return True
        except Exception:
            pass
    # Fallback: basic text via reportlab
    if canvas is not None:
        try:
            c = canvas.Canvas(str(out_path), pagesize=(1654, 1275))
            # Draw a border similar to SVG
            c.setStrokeColorRGB(0.1, 0.1, 0.1)
            c.rect(24, 24, 1606, 1227)
            c.setFont("Helvetica", 20)
            c.drawString(48, 1200, f"Project: {meta.get('project_name', '')}")
            c.drawString(48, 1160, f"Client: {meta.get('client', '')}")
            c.drawString(48, 1120, f"Sheet: {meta.get('sheet_name', '')}")
            c.drawString(1020, 1200, f"Generated by {meta.get('product', 'AlarmForge')} v{meta.get('version', '0.0.0')}")
            c.showPage()
            c.save()
            return True
        except Exception:
            pass
    return False


def export_title_block(folder: str | Path, meta: dict[str, str]) -> dict[str, str]:
    """Write title_block.svg and optional title_block.png/title_block.pdf into folder.

    meta keys include: project_name, client, sheet_name, author, date, product, version,
    job_number, revision, company. Returns dict with paths actually written.
    """
    p = Path(folder)
    p.mkdir(parents=True, exist_ok=True)
    svg_text = _build_svg(meta)
    svg_path = p / "title_block.svg"
    svg_path.write_text(svg_text, encoding="utf-8")

    out = {"svg": str(svg_path)}

    # Attempt PNG/PDF writes opportunistically
    png_path = p / "title_block.png"
    if _try_write_png(svg_text, png_path):
        out["png"] = str(png_path)

    pdf_path = p / "title_block.pdf"
    if _try_write_pdf(svg_text, pdf_path, meta):
        out["pdf"] = str(pdf_path)

    return out


def export_title_block_png_file(file_path: str | Path, meta: dict[str, str]) -> str:
    """Write a single PNG file to the given path from current SVG template/meta.

    Returns the absolute path written. Raises on failure to create PNG.
    """
    out_path = Path(file_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    svg_text = _build_svg(meta)
    if not _try_write_png(svg_text, out_path):
        raise RuntimeError("PNG export requires cairosvg or Pillow to be installed")
    return str(out_path)


def export_title_block_pdf_file(file_path: str | Path, meta: dict[str, str]) -> str:
    """Write a single PDF file to the given path from current SVG template/meta.

    Returns the absolute path written. Raises on failure to create PDF.
    """
    out_path = Path(file_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    svg_text = _build_svg(meta)
    if not _try_write_pdf(svg_text, out_path, meta):
        raise RuntimeError("PDF export requires cairosvg or reportlab to be installed")
    return str(out_path)


def export_title_block_svg_file(file_path: str | Path, meta: dict[str, str]) -> str:
    """Write a single SVG file to the given path.

    Returns the absolute path written.
    """
    out_path = Path(file_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    svg_text = _build_svg(meta)
    out_path.write_text(svg_text, encoding="utf-8")
    return str(out_path)
