name: Backend Task
description: Non-UI logic under backend/ (services, persistence, loaders)
labels: [area:backend, type:feature]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the service/storage/settings change.
      placeholder: e.g., Typed settings service with load/save
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Files/modules to change; avoid touching UI.
      placeholder: backend/settings/service.py, backend/store/catalog.py
  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: Black/Ruff clean
        - label: Tests added (round-trip, CRUD)
        - label: No module side effects
        - label: ≤300 LOC changed
