name: Frontend Task
description: UI work under frontend/ (Qt widgets, views, input)
labels: [area:frontend, type:feature]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the UI change.
      placeholder: e.g., Model Space shell with space selector and lock
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Files/components to touch; avoid unrelated edits.
      placeholder: frontend/widgets/ModelSpace.py, frontend/menus/ViewMenu.py
  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: Black/Ruff clean
        - label: Tests added/updated (signals, handlers)
        - label: No side effects in imports
        - label: ≤300 LOC changed

