name: Smoke - Windows (run_logs)

on:
  push:
  pull_request:

jobs:
  smoke-windows:
    name: Smoke (windows-latest)
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run headless smoke simulations
        run: py -3 -m run_logs.run_all_simulations
