name: Open PR for feat/cad-core-geometry-basics

on:
  workflow_dispatch:
  push:
    branches:
      - feat/cad-core-geometry-basics

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create or update PR
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = 'feat/cad-core-geometry-basics';
            const base = 'main';
            const prs = await github.paginate(github.rest.pulls.list, { owner, repo, state: 'open', head: `${owner}:${head}` });
            if (prs.length > 0) {
              core.info(`PR already open: #${prs[0].number}`);
              return;
            }
            const title = 'feat(cad_core): primitives + transforms with tests';
            const body = [
              'Adds Point/Vector/LineSegment and translate/scale/rotate with tests.',
              '',
              'Focused slice; pure functions; small LOC change.',
            ].join('\n');
            await github.rest.pulls.create({ owner, repo, head, base, title, body });

